import io

import pytest

import sambacc.nsswitch_loader

nsswitch1 = """\
# /etc/nsswitch.conf

passwd:    files
group:     files
hosts:     files dns
"""

nsswitch_winbind = """\
# /etc/nsswitch.conf

passwd:    files winbind
group:    files winbind
hosts:     files dns
"""

nsswitch_altfiles = """\
# /etc/nsswitch.conf

passwd:    files altfiles
group:    files altfiles
hosts:     files dns
"""


def test_loadlines():
    nss = sambacc.nsswitch_loader.NameServiceSwitchLoader("")
    nss.loadlines(nsswitch1.splitlines(True))
    assert len(nss.lines) == 3
    assert "passwd" in nss.idx
    assert "group" in nss.idx


def test_loadlines_skips_comments_and_blanks():
    nss = sambacc.nsswitch_loader.NameServiceSwitchLoader("")
    nss.loadlines(nsswitch1.splitlines(True))
    for line in nss.lines:
        assert not line.startswith("#")
        assert line.strip()


def test_dumplines():
    nss = sambacc.nsswitch_loader.NameServiceSwitchLoader("")
    nss.loadlines(nsswitch1.splitlines(True))
    output = "".join(nss.dumplines())
    assert output.startswith("# Generated by sambacc")
    assert "passwd:" in output
    assert "group:" in output
    assert "hosts:" in output


def test_readfp_writefp_roundtrip():
    nss = sambacc.nsswitch_loader.NameServiceSwitchLoader("")
    nss.readfp(io.StringIO(nsswitch1))
    fh = io.StringIO()
    nss.writefp(fh)
    output = fh.getvalue()
    assert "passwd:    files\n" in output
    assert "group:     files\n" in output
    assert "hosts:     files dns\n" in output


def test_winbind_enabled_false():
    nss = sambacc.nsswitch_loader.NameServiceSwitchLoader("")
    nss.loadlines(nsswitch1.splitlines(True))
    assert not nss.winbind_enabled()


def test_winbind_enabled_true():
    nss = sambacc.nsswitch_loader.NameServiceSwitchLoader("")
    nss.loadlines(nsswitch_winbind.splitlines(True))
    assert nss.winbind_enabled()


def test_ensure_winbind_enabled():
    nss = sambacc.nsswitch_loader.NameServiceSwitchLoader("")
    nss.loadlines(nsswitch1.splitlines(True))
    nss.ensure_winbind_enabled()
    assert nss.winbind_enabled()
    fh = io.StringIO()
    nss.writefp(fh)
    output = fh.getvalue()
    assert "passwd:    files winbind\n" in output
    assert "group:    files winbind\n" in output


def test_ensure_winbind_enabled_idempotent():
    nss = sambacc.nsswitch_loader.NameServiceSwitchLoader("")
    nss.loadlines(nsswitch_winbind.splitlines(True))
    nss.ensure_winbind_enabled()
    assert nss.winbind_enabled()
    assert len(nss.lines) == 3


def test_altfiles_enabled_false():
    nss = sambacc.nsswitch_loader.NameServiceSwitchLoader("")
    nss.loadlines(nsswitch1.splitlines(True))
    assert not nss.altfiles_enabled()


def test_altfiles_enabled_true():
    nss = sambacc.nsswitch_loader.NameServiceSwitchLoader("")
    nss.loadlines(nsswitch_altfiles.splitlines(True))
    assert nss.altfiles_enabled()


def test_ensure_altfiles_enabled():
    nss = sambacc.nsswitch_loader.NameServiceSwitchLoader("")
    nss.loadlines(nsswitch1.splitlines(True))
    nss.ensure_altfiles_enabled()
    assert nss.altfiles_enabled()
    fh = io.StringIO()
    nss.writefp(fh)
    output = fh.getvalue()
    assert "passwd:    files altfiles\n" in output
    assert "group:    files altfiles\n" in output


def test_ensure_altfiles_enabled_idempotent():
    nss = sambacc.nsswitch_loader.NameServiceSwitchLoader("")
    nss.loadlines(nsswitch_altfiles.splitlines(True))
    nss.ensure_altfiles_enabled()
    assert nss.altfiles_enabled()
    assert len(nss.lines) == 3


def test_find(tmp_path):
    nss_file = tmp_path / "nsswitch.conf"
    nss_file.write_text(nsswitch1)
    nss = sambacc.nsswitch_loader.find(paths=[str(nss_file)])
    assert nss.winbind_enabled() is False
    assert len(nss.lines) == 3


def test_find_first_path(tmp_path):
    nss_file = tmp_path / "nsswitch.conf"
    nss_file.write_text(nsswitch1)
    nonexistent = tmp_path / "does_not_exist"
    nss = sambacc.nsswitch_loader.find(paths=[str(nonexistent), str(nss_file)])
    assert len(nss.lines) == 3


def test_find_not_found(tmp_path):
    fake1 = tmp_path / "fake1"
    fake2 = tmp_path / "fake2"
    with pytest.raises(FileNotFoundError):
        sambacc.nsswitch_loader.find(paths=[str(fake1), str(fake2)])


def test_read_write_file(tmp_path):
    nss_file = tmp_path / "nsswitch.conf"
    nss_file.write_text(nsswitch1)
    nss = sambacc.nsswitch_loader.NameServiceSwitchLoader(str(nss_file))
    nss.read()
    nss.ensure_winbind_enabled()
    nss.write()
    content = nss_file.read_text()
    assert "passwd:    files winbind" in content
    assert "group:    files winbind" in content
